<a href="https://colab.research.google.com/github/asmb-09-12/Pytorch-Tutorial/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_2d = torch.randn(3,4)

In [3]:
tensor_2d

tensor([[ 0.7213, -0.1695,  1.0709, -0.6341],
        [ 0.7317, -0.7625,  0.1358, -0.5159],
        [ 1.3640, -1.0087,  0.6223,  1.9728]])

In [7]:
tensor_3d = torch.randn(3,4,5)

In [8]:
np1 = np.random.rand(4,5)

In [9]:
my_tensor = torch.tensor(np1)

In [10]:
my_tensor

tensor([[0.5833, 0.0082, 0.6264, 0.2612, 0.8456],
        [0.9357, 0.3274, 0.8472, 0.7379, 0.5203],
        [0.7705, 0.9943, 0.6870, 0.4401, 0.8375],
        [0.8426, 0.5216, 0.5951, 0.8667, 0.2083]], dtype=torch.float64)

In [12]:
zero_tensor = torch.zeros(4,5)
zero_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])